[tasks.build]
description = "Compila todos os serviços"
run = """
cd services/api-quarkus && ./mvnw compile
cd ../services/busca && go build ./...
cd ../conciliacao && go build ./...
"""

[tasks.test]
description = "Testa todos os serviços"
run = """
cd services/api-quarkus && ./mvnw test
cd ../services/busca && go test ./...
cd ../conciliacao && go test ./...
"""
